spring:
  application:
    name: booking-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      label: main
      # Enable config client retry
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 2
        multiplier: 1.5
        max-interval: 10000